map ctrl+shift+c copy_to_clipboard
map ctrl+shift+v paste_from_clipboard
map ctrl+w previous_window
map ctrl+esc close_window
map ctrl+w next_window
map ctrl+shift+w previous_window
map ctrl+equal change_font_size all +2.0
map ctrl+minus change_font_size all -2.0

window_padding_width 5.0

placement_strategy center
titlebar-only yes

# background_opacity 0.92
font_size 15.0

scrollback_lines 5000
remember_window_size  yes
hide_window_decorations titlebar-only
confirm_os_window_close 1

hide_window_decorations titlebar-only
a
# Tab Style
enabled_layouts splits:split_axis=horizontal
tab_bar_edge bottom
#tab_bar_margin_height 10.0 10.0
#tab_bar_margin_width 10.0
tab_bar_style fade
tab_fade 0.25 0.5 0.75 1
tab_separator " ┇"
#tab_separator " | "
#tab_separator " ▶ "
tab_bar_align left
tab_title_template "{fmt.fg.blue{bell_symbol}{activity_symbol}{fmt.fg.tab}{title}"
tab_activity_symbol ⚡
tab_title_template "{fmt.fg._EBCB8B}{index}: {fmt.fg.tab}{title.split()[0] == title.split()[-1] and title.split()[0] or title.split()[0] + ' ' + title.split()[-1]}"
active_tab_title_template
active_tab_foreground #ebdbb2
active_tab_background #282C3B
active_tab_font_style bold
inactive_tab_foreground #000000
inactive_tab_background #343c63

inactive_tab_font_style bold

background_opacity 1
window_padding_width  5
# BEGIN_KITTY_THEME
# neobones_dark
include ~/.config/starship.toml
include material-ocean.conf
# END_KITTY_THEME

font_family          JetBrainsMono Nerd Font 
bold_font            JetBrainsMono Nerd Font 
italic_font           JetBrainsMono Nerd Font 
bold_italic_font     JetBrainsMono Nerd Font 

scrollback_lines 2000
mouse_hide_wait 3.0
kitty_mod ctrl+shift
open_url_modifiers kitty_mod
open_url_with default
clipboard_control write-clipboard write-primary
window_padding_width 2 2 1 2
cursor_shape block
cursor_blink_interface 1
cursor_blink_interval 0.5
cursor_shape_block_codepoint 102500
cursor_shape_smoothing 1
# tab_bar_align left

editor /opt/homebrew/bin/nvim

# active_tab_background #1d2021
# active_tab_foreground #fefefe
# active_tab_font_style bold
# inactive_tab_background #1d2021
# inactive_tab_foreground #a89984
# inactive_tab_font_style normal

# tab_bar_background #3c3836
# tab_bar_foreground #ebdbb2
# tab_bar_edge_top #3c3836
# tab_bar_edge_bottom #3c3836
# tab_bar_edge_color #3c3836
# tab_bar_active_color #d5c4a1
# tab_bar_idle_color #bdae93
# wayland_titlebar_color #303030
#
#
#
# Set the layout for the current tab
layout tall
# Set the working directory for windows in the current tab
cd ~/Documents
# Create a window and run the specified command in it
launch zsh
